#!/bin/bash
RANDOM_SEED=1
POOL_SIZE=15
STOCK_SIZE=10
LISTE_CROISSANTE_SIZE=50
NOMBRE_TIRAGE=10
ITERATION=1000
ARRAY_MAX_SIZE=20
INNER_MAX_SIZE=5
TYPE="ALL"

if [ "$1" != "" ]
then TYPE=$1
fi

echo "OS2L BENCH"
if [ "$TYPE" == "ALL" ]
then
java -XX:-PrintGCDetails -jar Optimized-Small-Set-Library.jar INNER $RANDOM_SEED $POOL_SIZE $STOCK_SIZE $LISTE_CROISSANTE_SIZE $NOMBRE_TIRAGE $ITERATION $ARRAY_MAX_SIZE $INNER_MAX_SIZE
java -XX:-PrintGCDetails -jar Optimized-Small-Set-Library.jar ARRAY $RANDOM_SEED $POOL_SIZE $STOCK_SIZE $LISTE_CROISSANTE_SIZE $NOMBRE_TIRAGE $ITERATION $ARRAY_MAX_SIZE $INNER_MAX_SIZE
java -XX:-PrintGCDetails -jar Optimized-Small-Set-Library.jar HASH $RANDOM_SEED $POOL_SIZE $STOCK_SIZE $LISTE_CROISSANTE_SIZE $NOMBRE_TIRAGE $ITERATION $ARRAY_MAX_SIZE $INNER_MAX_SIZE

else
java -XX:-PrintGCDetails -jar Optimized-Small-Set-Library.jar $TYPE $RANDOM_SEED $POOL_SIZE $STOCK_SIZE $LISTE_CROISSANTE_SIZE $NOMBRE_TIRAGE $ITERATION $ARRAY_MAX_SIZE $INNER_MAX_SIZE

fi
